Fix/out of bounds while decoding
georust/polyline pull request #37
Opened 2024-04-24 16:32 UTC by mattiZed

This PR is a fix for #36.

I'd like to add that this issue was probably not caught earlier because the "broken_string" test is a bit misleading. While the polyline in that test is "broken" it still decodes fine, the decoded data is just meaningless. It would only trigger "should_panic" because of the test's assertion not holding. I have refactored another test with a similar issue.
 
I have also added a test with an input that actually causes the out-of-bounds error.

On my machine, there is a performance hit:

```
     Running benches/benchmarks.rs (target/release/deps/benchmarks-47700460fb2f8668)
bench encode: 1000 coordinates
                        time:   [50.426 µs 50.577 µs 50.744 µs]
                        change: [-11.202% -10.880% -10.555%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 12 outliers among 100 measurements (12.00%)
  9 (9.00%) high mild
  3 (3.00%) high severe

bench decode: 21502 coordinates
                        time:   [231.81 µs 233.17 µs 234.88 µs]
                        change: [+4.7448% +5.2551% +5.7437%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 5 outliers among 100 measurements (5.00%)
  5 (5.00%) high severe

bench polyline6 decoding
                        time:   [40.434 ns 40.524 ns 40.623 ns]
                        change: [+9.1684% +9.8057% +10.405%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 10 outliers among 100 measurements (10.00%)
  4 (4.00%) high mild
  6 (6.00%) high severe

bench HUGE polyline6 decoding
                        time:   [30.727 µs 30.855 µs 31.013 µs]
                        change: [+12.223% +12.654% +13.046%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe
```

I can't tell if this is still acceptable.

2024-04-24 18:40 UTC, mattiZed commented
I have gone back and forth on this a bit (as you can probably tell from the commits) - I'm happy with this version now, the performance hit seems very small.

2024-04-25 18:20 UTC, urschrei requested changes
No need to `unwrap()` here: we return a `Result` from this function so we can check for `Err` values and pass them up the chain.

2024-04-25 18:20 UTC, urschrei commented on src/lib.rs
> +        let (latitude_change, new_index) = trans(chars, index).unwrap();
```suggestion
        let (latitude_change, new_index) = trans(chars, index)?;
```

2024-04-25 18:20 UTC, urschrei commented on src/lib.rs
> +        let (longitude_change, new_index) = trans(chars, new_index).unwrap();
```suggestion
        let (longitude_change, new_index) = trans(chars, new_index)?;
```

2024-04-25 18:21 UTC, urschrei commented
Perf regression on decodes is 10 - 12 %. I can live with that unless someone else has a better suggestion.

2024-04-25 20:08 UTC, urschrei commented
Why aren't our tests running 🤔

2024-04-25 20:19 UTC, urschrei approved these changes

2024-04-25 20:26 UTC, urschrei commented
@mattiZed Thanks, this looks OK to me. Could you also update the changelog (under `Unreleased`)? Just short entry noting the change and perf regression. I'll leave this open til tomorrow and then merge unless anyone else has input.

2024-04-26 05:01 UTC, mattiZed commented
> @mattiZed Thanks, this looks OK to me. Could you also update the changelog (under `Unreleased`)? Just a short entry noting the change and perf regression. I'll leave this open til tomorrow and then merge unless anyone else has input.

Sure thing, done!

2024-04-26 15:19 UTC, merged